name: Build and test the app
on: 
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Setup
        run: make setup
      - name: Tests
        run: make test
      - name: Linter
        run: make lint
